export const styles: { [key: string]: React.CSSProperties } = {
    container: {
        maxWidth: '800px',
        margin: '0 auto',
        padding: '20px',
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    title: {
        fontSize: '2.5rem',
        color: '#2c3e50',
        marginBottom: '30px',
        textAlign: 'center',
    },
    inputContainer: {
        display: 'flex',
        gap: '10px',
        marginBottom: '30px',
    },
    input: {
        flex: 1,
        padding: '12px 16px',
        fontSize: '1rem',
        border: '2px solid #e0e0e0',
        borderRadius: '8px',
        outline: 'none',
        transition: 'border-color 0.2s',
    },
    addButton: {
        padding: '12px 24px',
        fontSize: '1rem',
        backgroundColor: '#3498db',
        color: 'white',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: '600',
        transition: 'background-color 0.2s',
    },
    todoList: {
        listStyle: 'none',
        padding: 0,
        margin: 0,
    },
    todoItem: {
        backgroundColor: 'white',
        border: '1px solid #e0e0e0',
        borderRadius: '12px',
        padding: '20px',
        marginBottom: '12px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        transition: 'transform 0.2s, box-shadow 0.2s',
        boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
    },
    completedItem: {
        backgroundColor: '#f8f9fa',
        opacity: 0.8,
    },
    todoContent: {
        flex: 1,
        marginRight: '16px',
    },
    todoInfo: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        marginBottom: '8px',
    },
    todoTitle: {
        fontSize: '1.1rem',
        color: '#2c3e50',
        fontWeight: '500',
    },
    completedText: {
        textDecoration: 'line-through',
        color: '#95a5a6',
    },
    statusBadge: {
        padding: '4px 12px',
        borderRadius: '12px',
        fontSize: '0.85rem',
        fontWeight: '600',
    },
    pendingBadge: {
        backgroundColor: '#fff3cd',
        color: '#856404',
    },
    completedBadge: {
        backgroundColor: '#d4edda',
        color: '#155724',
    },
    dateInfo: {
        fontSize: '0.85rem',
        color: '#7f8c8d',
    },
    buttonGroup: {
        display: 'flex',
        gap: '8px',
        flexWrap: 'wrap',
    },
    button: {
        padding: '8px 14px',
        fontSize: '0.9rem',
        border: 'none',
        borderRadius: '6px',
        cursor: 'pointer',
        fontWeight: '500',
        transition: 'all 0.2s',
    },
    completeButton: {
        backgroundColor: '#27ae60',
        color: 'white',
    },
    pendingButton: {
        backgroundColor: '#f39c12',
        color: 'white',
    },
    editButton: {
        backgroundColor: '#3498db',
        color: 'white',
    },
    deleteButton: {
        backgroundColor: '#e74c3c',
        color: 'white',
    },
    saveButton: {
        backgroundColor: '#27ae60',
        color: 'white',
    },
    cancelButton: {
        backgroundColor: '#95a5a6',
        color: 'white',
    },
    editContainer: {
        display: 'flex',
        gap: '12px',
        width: '100%',
        alignItems: 'center',
    },
    editInput: {
        flex: 1,
        padding: '10px 14px',
        fontSize: '1rem',
        border: '2px solid #3498db',
        borderRadius: '6px',
        outline: 'none',
    },
};